#pragma once

namespace Ravid
{
	namespace Miscellaneous
	{
		enum ECPUInstructionType
		{
			ECPUInstructionType_SSE = 0x01,                          //
			ECPUInstructionType_SSE2 = 0x02,                          //
			ECPUInstructionType_SSE_SSE2 = 0x03,
			ECPUInstructionType_SSE3 = 0x04,                          //
			ECPUInstructionType_SSE_SSE3 = 0x05,
			ECPUInstructionType_SSE2_SSE3 = 0x06,
			ECPUInstructionType_SSE_SSE2_SSE3 = 0x07,
			ECPUInstructionType_SSE4 = 0x08,                          //
			ECPUInstructionType_SSE_SSE4 = 0x09,
			ECPUInstructionType_SSE2_SSE4 = 0x0a,
			ECPUInstructionType_SSE_SSE2_SSE4 = 0x0b,
			ECPUInstructionType_SSE3_SSE4 = 0x0c,
			ECPUInstructionType_SSE_SSE3_SSE4 = 0x0d,
			ECPUInstructionType_SSE2_SSE3_SSE4 = 0x0e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4 = 0x0f,
			ECPUInstructionType_XOP = 0x10,                          //
			ECPUInstructionType_SSE_XOP = 0x11,
			ECPUInstructionType_SSE2_XOP = 0x12,
			ECPUInstructionType_SSE_SSE2_XOP = 0x13,
			ECPUInstructionType_SSE3_XOP = 0x14,
			ECPUInstructionType_SSE_SSE3_XOP = 0x15,
			ECPUInstructionType_SSE2_SSE3_XOP = 0x16,
			ECPUInstructionType_SSE_SSE2_SSE3_XOP = 0x17,
			ECPUInstructionType_SSE4_XOP = 0x18,
			ECPUInstructionType_SSE_SSE4_XOP = 0x19,
			ECPUInstructionType_SSE2_SSE4_XOP = 0x1a,
			ECPUInstructionType_SSE_SSE2_SSE4_XOP = 0x1b,
			ECPUInstructionType_SSE3_SSE4_XOP = 0x1c,
			ECPUInstructionType_SSE_SSE3_SSE4_XOP = 0x1d,
			ECPUInstructionType_SSE2_SSE3_SSE4_XOP = 0x1e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_XOP = 0x1f,
			ECPUInstructionType_AVX = 0x20,                          //
			ECPUInstructionType_SSE_AVX = 0x21,
			ECPUInstructionType_SSE2_AVX = 0x22,
			ECPUInstructionType_SSE_SSE2_AVX = 0x23,
			ECPUInstructionType_SSE3_AVX = 0x24,
			ECPUInstructionType_SSE_SSE3_AVX = 0x25,
			ECPUInstructionType_SSE2_SSE3_AVX = 0x26,
			ECPUInstructionType_SSE_SSE2_SSE3_AVX = 0x27,
			ECPUInstructionType_SSE4_AVX = 0x28,
			ECPUInstructionType_SSE_SSE4_AVX = 0x29,
			ECPUInstructionType_SSE2_SSE4_AVX = 0x2a,
			ECPUInstructionType_SSE_SSE2_SSE4_AVX = 0x2b,
			ECPUInstructionType_SSE3_SSE4_AVX = 0x2c,
			ECPUInstructionType_SSE_SSE3_SSE4_AVX = 0x2d,
			ECPUInstructionType_SSE2_SSE3_SSE4_AVX = 0x2e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_AVX = 0x2f,
			ECPUInstructionType_XOP_AVX = 0x30,
			ECPUInstructionType_SSE_XOP_AVX = 0x31,
			ECPUInstructionType_SSE2_XOP_AVX = 0x32,
			ECPUInstructionType_SSE_SSE2_XOP_AVX = 0x33,
			ECPUInstructionType_SSE3_XOP_AVX = 0x34,
			ECPUInstructionType_SSE_SSE3_XOP_AVX = 0x35,
			ECPUInstructionType_SSE2_SSE3_XOP_AVX = 0x36,
			ECPUInstructionType_SSE_SSE2_SSE3_XOP_AVX = 0x37,
			ECPUInstructionType_SSE4_XOP_AVX = 0x38,
			ECPUInstructionType_SSE_SSE4_XOP_AVX = 0x39,
			ECPUInstructionType_SSE2_SSE4_XOP_AVX = 0x3a,
			ECPUInstructionType_SSE_SSE2_SSE4_XOP_AVX = 0x3b,
			ECPUInstructionType_SSE3_SSE4_XOP_AVX = 0x3c,
			ECPUInstructionType_SSE_SSE3_SSE4_XOP_AVX = 0x3d,
			ECPUInstructionType_SSE2_SSE3_SSE4_XOP_AVX = 0x3e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_XOP_AVX = 0x3f,
			ECPUInstructionType_AVX2 = 0x40,                           //
			ECPUInstructionType_SSE_AVX2 = 0x41,
			ECPUInstructionType_SSE2_AVX2 = 0x42,
			ECPUInstructionType_SSE_SSE2_AVX2 = 0x43,
			ECPUInstructionType_SSE3_AVX2 = 0x44,
			ECPUInstructionType_SSE_SSE3_AVX2 = 0x45,
			ECPUInstructionType_SSE2_SSE3_AVX2 = 0x46,
			ECPUInstructionType_SSE_SSE2_SSE3_AVX2 = 0x47,
			ECPUInstructionType_SSE4_AVX2 = 0x48,
			ECPUInstructionType_SSE_SSE4_AVX2 = 0x49,
			ECPUInstructionType_SSE2_SSE4_AVX2 = 0x4a,
			ECPUInstructionType_SSE_SSE2_SSE4_AVX2 = 0x4b,
			ECPUInstructionType_SSE3_SSE4_AVX2 = 0x4c,
			ECPUInstructionType_SSE_SSE3_SSE4_AVX2 = 0x4d,
			ECPUInstructionType_SSE2_SSE3_SSE4_AVX2 = 0x4e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_AVX2 = 0x4f,
			ECPUInstructionType_XOP_AVX2 = 0x50,
			ECPUInstructionType_SSE_XOP_AVX2 = 0x51,
			ECPUInstructionType_SSE2_XOP_AVX2 = 0x52,
			ECPUInstructionType_SSE_SSE2_XOP_AVX2 = 0x53,
			ECPUInstructionType_SSE3_XOP_AVX2 = 0x54,
			ECPUInstructionType_SSE_SSE3_XOP_AVX2 = 0x55,
			ECPUInstructionType_SSE2_SSE3_XOP_AVX2 = 0x56,
			ECPUInstructionType_SSE_SSE2_SSE3_XOP_AVX2 = 0x57,
			ECPUInstructionType_SSE4_XOP_AVX2 = 0x58,
			ECPUInstructionType_SSE_SSE4_XOP_AVX2 = 0x59,
			ECPUInstructionType_SSE2_SSE4_XOP_AVX2 = 0x5a,
			ECPUInstructionType_SSE_SSE2_SSE4_XOP_AVX2 = 0x5b,
			ECPUInstructionType_SSE3_SSE4_XOP_AVX2 = 0x5c,
			ECPUInstructionType_SSE_SSE3_SSE4_XOP_AVX2 = 0x5d,
			ECPUInstructionType_SSE2_SSE3_SSE4_XOP_AVX2 = 0x5e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_XOP_AVX2 = 0x5f,
			ECPUInstructionType_AVX_AVX2 = 0x60,
			ECPUInstructionType_SSE_AVX_AVX2 = 0x61,
			ECPUInstructionType_SSE2_AVX_AVX2 = 0x62,
			ECPUInstructionType_SSE_SSE2_AVX_AVX2 = 0x63,
			ECPUInstructionType_SSE3_AVX_AVX2 = 0x64,
			ECPUInstructionType_SSE_SSE3_AVX_AVX2 = 0x65,
			ECPUInstructionType_SSE2_SSE3_AVX_AVX2 = 0x66,
			ECPUInstructionType_SSE_SSE2_SSE3_AVX_AVX2 = 0x67,
			ECPUInstructionType_SSE4_AVX_AVX2 = 0x68,
			ECPUInstructionType_SSE_SSE4_AVX_AVX2 = 0x69,
			ECPUInstructionType_SSE2_SSE4_AVX_AVX2 = 0x6a,
			ECPUInstructionType_SSE_SSE2_SSE4_AVX_AVX2 = 0x6b,
			ECPUInstructionType_SSE3_SSE4_AVX_AVX2 = 0x6c,
			ECPUInstructionType_SSE_SSE3_SSE4_AVX_AVX2 = 0x6d,
			ECPUInstructionType_SSE2_SSE3_SSE4_AVX_AVX2 = 0x6e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_AVX_AVX2 = 0x6f,
			ECPUInstructionType_XOP_AVX_AVX2 = 0x70,
			ECPUInstructionType_SSE_XOP_AVX_AVX2 = 0x71,
			ECPUInstructionType_SSE2_XOP_AVX_AVX2 = 0x72,
			ECPUInstructionType_SSE_SSE2_XOP_AVX_AVX2 = 0x73,
			ECPUInstructionType_SSE3_XOP_AVX_AVX2 = 0x74,
			ECPUInstructionType_SSE_SSE3_XOP_AVX_AVX2 = 0x75,
			ECPUInstructionType_SSE2_SSE3_XOP_AVX_AVX2 = 0x76,
			ECPUInstructionType_SSE_SSE2_SSE3_XOP_AVX_AVX2 = 0x77,
			ECPUInstructionType_SSE4_XOP_AVX_AVX2 = 0x78,
			ECPUInstructionType_SSE_SSE4_XOP_AVX_AVX2 = 0x79,
			ECPUInstructionType_SSE2_SSE4_XOP_AVX_AVX2 = 0x7a,
			ECPUInstructionType_SSE_SSE2_SSE4_XOP_AVX_AVX2 = 0x7b,
			ECPUInstructionType_SSE3_SSE4_XOP_AVX_AVX2 = 0x7c,
			ECPUInstructionType_SSE_SSE3_SSE4_XOP_AVX_AVX2 = 0x7d,
			ECPUInstructionType_SSE2_SSE3_SSE4_XOP_AVX_AVX2 = 0x7e,
			ECPUInstructionType_SSE_SSE2_SSE3_SSE4_XOP_AVX_AVX2 = 0x7f,

		};

		enum EOperatingSystemType
		{
			EOperatingSystemType_Unknown = 0,
			EOperatingSystemType_WindowsXP,
			EOperatingSystemType_WindowsXPProfessionalX64,
			EOperatingSystemType_WindowsServer2003,
			EOperatingSystemType_WindowsHomeServer,
			EOperatingSystemType_WindowsServer2003R2,
			EOperatingSystemType_WindowsVista,
			EOperatingSystemType_WindowsServer2008,
			EOperatingSystemType_WindowsServer2008R2,
			EOperatingSystemType_Windows7,
			EOperatingSystemType_WindowsServer2012,
			EOperatingSystemType_Windows8,
			EOperatingSystemType_WindowsServer2012R2,
			EOperatingSystemType_Windows8_1,
			EOperatingSystemType_Windows10,
			EOperatingSystemType_LaterThanWindows10,
		};
	}
}
///