#pragma once

#include "RavidPoint.h"
#include "RavidGeometry.h"

template <typename T>
class AFX_EXT_CLASS CRavidLine : public CRavidGeometry
{
public:
	RavidUseDynamicCreation(this);

	static_assert(CheckIntegerAndRealNumber<T>::value, "CRavidLine template class is able to use type within int, long long, float and double.");

	CRavidLine();
	virtual ~CRavidLine();

	virtual bool SetExclusiveRegion(_In_ CRavidGeometryArray* pExclusiveRegion);
	virtual bool SetExclusiveRegion(_In_ CRavidGeometryArray& refExclusiveRegion);

	virtual bool AddExclusiveRegion(_In_ CRavidGeometry* pGeometry);
	virtual bool AddExclusiveRegion(_In_ CRavidGeometry& refGeometry);

	virtual CRavidGeometryArray* GetExclusiveRegion() const;

	virtual void ClearExclusiveRegion();

	virtual bool IsThereExclusiveRegion() const;

	//////////////////////////////////////////////////////////////////////////
	// Copy constructor
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	CRavidLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	CRavidLine(_In_ T a, _In_ T b, _In_ T c);
	CRavidLine(_In_ const POINT& point);
	CRavidLine(_In_ POINT* pPoint);
	CRavidLine(_In_ const SIZE& size);
	CRavidLine(_In_ SIZE* pSize);
	CRavidLine(_In_ const CRavidPoint<int>& point);
	CRavidLine(_In_ CRavidPoint<int>* pPoint);
	CRavidLine(_In_ const CRavidPoint<long long>& point);
	CRavidLine(_In_ CRavidPoint<long long>* pPoint);
	CRavidLine(_In_ const CRavidPoint<float>& point);
	CRavidLine(_In_ CRavidPoint<float>* pPoint);
	CRavidLine(_In_ const CRavidPoint<double>& point);
	CRavidLine(_In_ CRavidPoint<double>* pPoint);
	CRavidLine(_In_ const CRavidPoint<int>& rpCenter, _In_ double dblAngle);
	CRavidLine(_In_ CRavidPoint<int>* pRpCenter, _In_ double dblAngle);
	CRavidLine(_In_ const CRavidPoint<long long>& rpCenter, _In_ double dblAngle);
	CRavidLine(_In_ CRavidPoint<long long>* pRpCenter, _In_ double dblAngle);
	CRavidLine(_In_ const CRavidPoint<float>& rpCenter, _In_ double dblAngle);
	CRavidLine(_In_ CRavidPoint<float>* pRpCenter, _In_ double dblAngle);
	CRavidLine(_In_ const CRavidPoint<double>& rpCenter, _In_ double dblAngle);
	CRavidLine(_In_ CRavidPoint<double>* pRpCenter, _In_ double dblAngle);
	CRavidLine(_In_ const CRavidPoint<int>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ CRavidPoint<int>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ const CRavidPoint<long long>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ CRavidPoint<long long>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ const CRavidPoint<float>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ CRavidPoint<float>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ const CRavidPoint<double>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ CRavidPoint<double>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	CRavidLine(_In_ const POINT& point1, _In_ const POINT& point2);
	CRavidLine(_In_ POINT* pPoint1, _In_ POINT* pPoint2);
	CRavidLine(_In_ const CRavidPoint<int>& point1, _In_ const CRavidPoint<int>& point2);
	CRavidLine(_In_ CRavidPoint<int>* pPoint1, _In_ CRavidPoint<int>* pPoint2);
	CRavidLine(_In_ const CRavidPoint<long long>& point1, _In_ const CRavidPoint<long long>& point2);
	CRavidLine(_In_ CRavidPoint<long long>* pPoint1, _In_ CRavidPoint<long long>* pPoint2);
	CRavidLine(_In_ const CRavidPoint<float>& point1, _In_ const CRavidPoint<float>& point2);
	CRavidLine(_In_ CRavidPoint<float>* pPoint1, _In_ CRavidPoint<float>* pPoint2);
	CRavidLine(_In_ const CRavidPoint<double>& point1, _In_ const CRavidPoint<double>& point2);
	CRavidLine(_In_ CRavidPoint<double>* pPoint1, _In_ CRavidPoint<double>* pPoint2);
	CRavidLine(_In_ const CRavidLine<int>& line);
	CRavidLine(_In_ CRavidLine<int>* pLine);
	CRavidLine(_In_ const CRavidLine<long long>& line);
	CRavidLine(_In_ CRavidLine<long long>* pLine);
	CRavidLine(_In_ const CRavidLine<float>& line);
	CRavidLine(_In_ CRavidLine<float>* pLine);
	CRavidLine(_In_ const CRavidLine<double>& line);
	CRavidLine(_In_ CRavidLine<double>* pLine);
	CRavidLine(_In_ const RECT& rect);
	CRavidLine(_In_ RECT* pRect);
	CRavidLine(_In_ const CRavidRect<int>& rect);
	CRavidLine(_In_ CRavidRect<int>* pRect);
	CRavidLine(_In_ const CRavidRect<long long>& rect);
	CRavidLine(_In_ CRavidRect<long long>* pRect);
	CRavidLine(_In_ const CRavidRect<float>& rect);
	CRavidLine(_In_ CRavidRect<float>* pRect);
	CRavidLine(_In_ const CRavidRect<double>& rect);
	CRavidLine(_In_ CRavidRect<double>* pRect);
	//////////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////////
	// Assignment operator
	void operator=(_In_ const POINT& point);
	void operator=(_In_ POINT* pPoint);
	void operator=(_In_ const SIZE& size);
	void operator=(_In_ SIZE* pSize);
	void operator=(_In_ const CRavidPoint<int>& point);
	void operator=(_In_ CRavidPoint<int>* pPoint);
	void operator=(_In_ const CRavidPoint<long long>& point);
	void operator=(_In_ CRavidPoint<long long>* pPoint);
	void operator=(_In_ const CRavidPoint<float>& point);
	void operator=(_In_ CRavidPoint<float>* pPoint);
	void operator=(_In_ const CRavidPoint<double>& point);
	void operator=(_In_ CRavidPoint<double>* pPoint);
	void operator=(_In_ const CRavidLine<int>& line);
	void operator=(_In_ CRavidLine<int>* pLine);
	void operator=(_In_ const CRavidLine<long long>& line);
	void operator=(_In_ CRavidLine<long long>* pLine);
	void operator=(_In_ const CRavidLine<float>& line);
	void operator=(_In_ CRavidLine<float>* pLine);
	void operator=(_In_ const CRavidLine<double>& line);
	void operator=(_In_ CRavidLine<double>* pLine);
	void operator=(_In_ const RECT& rect);
	void operator=(_In_ RECT* pRect);
	void operator=(_In_ const CRavidRect<int>& rect);
	void operator=(_In_ CRavidRect<int>* pRect);
	void operator=(_In_ const CRavidRect<long long>& rect);
	void operator=(_In_ CRavidRect<long long>* pRect);
	void operator=(_In_ const CRavidRect<float>& rect);
	void operator=(_In_ CRavidRect<float>* pRect);
	void operator=(_In_ const CRavidRect<double>& rect);
	void operator=(_In_ CRavidRect<double>* pRect);
	//////////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////////
	// Comparison operator
	bool operator==(_In_ const CRavidLine<int>& line);
	bool operator==(_In_ const CRavidLine<long long>& line);
	bool operator==(_In_ const CRavidLine<float>& line);
	bool operator==(_In_ const CRavidLine<double>& line);
	bool operator==(_In_ const CRavidRect<int>& rect);
	bool operator==(_In_ const CRavidRect<long long>& rect);
	bool operator==(_In_ const CRavidRect<float>& rect);
	bool operator==(_In_ const CRavidRect<double>& rect);

	bool operator!=(_In_ const CRavidLine<int>& line);
	bool operator!=(_In_ const CRavidLine<long long>& line);
	bool operator!=(_In_ const CRavidLine<float>& line);
	bool operator!=(_In_ const CRavidLine<double>& line);
	bool operator!=(_In_ const CRavidRect<int>& rect);
	bool operator!=(_In_ const CRavidRect<long long>& rect);
	bool operator!=(_In_ const CRavidRect<float>& rect);
	bool operator!=(_In_ const CRavidRect<double>& rect);
	//////////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////////
	// Arithmetic and assignment operator
	virtual void operator+=(_In_ const int& value);
	virtual void operator+=(_In_ const long long& value);
	virtual void operator+=(_In_ const float& value);
	virtual void operator+=(_In_ const double& value);
	virtual void operator+=(_In_ const POINT& point);
	virtual void operator+=(_In_ const SIZE& size);
	void operator+=(_In_ const RECT& rect);
	virtual void operator+=(_In_ const CRavidPoint<int>& point);
	virtual void operator+=(_In_ const CRavidPoint<long long>& point);
	virtual void operator+=(_In_ const CRavidPoint<float>& point);
	virtual void operator+=(_In_ const CRavidPoint<double>& point);
	void operator+=(_In_ const CRavidLine<int>& line);
	void operator+=(_In_ const CRavidLine<long long>& line);
	void operator+=(_In_ const CRavidLine<float>& line);
	void operator+=(_In_ const CRavidLine<double>& line);
	void operator+=(_In_ const CRavidRect<int>& rect);
	void operator+=(_In_ const CRavidRect<long long>& rect);
	void operator+=(_In_ const CRavidRect<float>& rect);
	void operator+=(_In_ const CRavidRect<double>& rect);

	virtual void operator-=(_In_ const int& value);
	virtual void operator-=(_In_ const long long& value);
	virtual void operator-=(_In_ const float& value);
	virtual void operator-=(_In_ const double& value);
	virtual void operator-=(_In_ const POINT& point);
	virtual void operator-=(_In_ const SIZE& size);
	void operator-=(_In_ const RECT& rect);
	virtual void operator-=(_In_ const CRavidPoint<int>& point);
	virtual void operator-=(_In_ const CRavidPoint<long long>& point);
	virtual void operator-=(_In_ const CRavidPoint<float>& point);
	virtual void operator-=(_In_ const CRavidPoint<double>& point);
	void operator-=(_In_ const CRavidLine<int>& line);
	void operator-=(_In_ const CRavidLine<long long>& line);
	void operator-=(_In_ const CRavidLine<float>& line);
	void operator-=(_In_ const CRavidLine<double>& line);
	void operator-=(_In_ const CRavidRect<int>& rect);
	void operator-=(_In_ const CRavidRect<long long>& rect);
	void operator-=(_In_ const CRavidRect<float>& rect);
	void operator-=(_In_ const CRavidRect<double>& rect);

	virtual void operator*=(_In_ const int& value);
	virtual void operator*=(_In_ const long long& value);
	virtual void operator*=(_In_ const float& value);
	virtual void operator*=(_In_ const double& value);
	virtual void operator*=(_In_ const POINT& point);
	virtual void operator*=(_In_ const SIZE& size);
	void operator*=(_In_ const RECT& rect);
	virtual void operator*=(_In_ const CRavidPoint<int>& point);
	virtual void operator*=(_In_ const CRavidPoint<long long>& point);
	virtual void operator*=(_In_ const CRavidPoint<float>& point);
	virtual void operator*=(_In_ const CRavidPoint<double>& point);
	void operator*=(_In_ const CRavidLine<int>& line);
	void operator*=(_In_ const CRavidLine<long long>& line);
	void operator*=(_In_ const CRavidLine<float>& line);
	void operator*=(_In_ const CRavidLine<double>& line);
	void operator*=(_In_ const CRavidRect<int>& rect);
	void operator*=(_In_ const CRavidRect<long long>& rect);
	void operator*=(_In_ const CRavidRect<float>& rect);
	void operator*=(_In_ const CRavidRect<double>& rect);

	virtual void operator/=(_In_ const int& value);
	virtual void operator/=(_In_ const long long& value);
	virtual void operator/=(_In_ const float& value);
	virtual void operator/=(_In_ const double& value);
	virtual void operator/=(_In_ const POINT& point);
	virtual void operator/=(_In_ const SIZE& size);
	void operator/=(_In_ const RECT& rect);
	virtual void operator/=(_In_ const CRavidPoint<int>& point);
	virtual void operator/=(_In_ const CRavidPoint<long long>& point);
	virtual void operator/=(_In_ const CRavidPoint<float>& point);
	virtual void operator/=(_In_ const CRavidPoint<double>& point);
	void operator/=(_In_ const CRavidLine<int>& line);
	void operator/=(_In_ const CRavidLine<long long>& line);
	void operator/=(_In_ const CRavidLine<float>& line);
	void operator/=(_In_ const CRavidLine<double>& line);
	void operator/=(_In_ const CRavidRect<int>& rect);
	void operator/=(_In_ const CRavidRect<long long>& rect);
	void operator/=(_In_ const CRavidRect<float>& rect);
	void operator/=(_In_ const CRavidRect<double>& rect);
	//////////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////////
	// Arithmetic operator
	CRavidLine<double> operator+(_In_ const int& value);
	CRavidLine<double> operator+(_In_ const long long& value);
	CRavidLine<double> operator+(_In_ const float& value);
	CRavidLine<double> operator+(_In_ const double& value);
	CRavidLine<double> operator+(_In_ const POINT& point);
	CRavidLine<double> operator+(_In_ const SIZE& size);
	CRavidLine<double> operator+(_In_ const RECT& rect);
	CRavidLine<double> operator+(_In_ const CRavidPoint<int>& point);
	CRavidLine<double> operator+(_In_ const CRavidPoint<long long>& point);
	CRavidLine<double> operator+(_In_ const CRavidPoint<float>& point);
	CRavidLine<double> operator+(_In_ const CRavidPoint<double>& point);
	CRavidLine<double> operator+(_In_ const CRavidLine<int>& line);
	CRavidLine<double> operator+(_In_ const CRavidLine<long long>& line);
	CRavidLine<double> operator+(_In_ const CRavidLine<float>& line);
	CRavidLine<double> operator+(_In_ const CRavidLine<double>& line);
	CRavidLine<double> operator+(_In_ const CRavidRect<int>& rect);
	CRavidLine<double> operator+(_In_ const CRavidRect<long long>& rect);
	CRavidLine<double> operator+(_In_ const CRavidRect<float>& rect);
	CRavidLine<double> operator+(_In_ const CRavidRect<double>& rect);

	CRavidLine<double> operator-(_In_ const int& value);
	CRavidLine<double> operator-(_In_ const long long& value);
	CRavidLine<double> operator-(_In_ const float& value);
	CRavidLine<double> operator-(_In_ const double& value);
	CRavidLine<double> operator-(_In_ const POINT& point);
	CRavidLine<double> operator-(_In_ const SIZE& size);
	CRavidLine<double> operator-(_In_ const RECT& rect);
	CRavidLine<double> operator-(_In_ const CRavidPoint<int>& point);
	CRavidLine<double> operator-(_In_ const CRavidPoint<long long>& point);
	CRavidLine<double> operator-(_In_ const CRavidPoint<float>& point);
	CRavidLine<double> operator-(_In_ const CRavidPoint<double>& point);
	CRavidLine<double> operator-(_In_ const CRavidLine<int>& line);
	CRavidLine<double> operator-(_In_ const CRavidLine<long long>& line);
	CRavidLine<double> operator-(_In_ const CRavidLine<float>& line);
	CRavidLine<double> operator-(_In_ const CRavidLine<double>& line);
	CRavidLine<double> operator-(_In_ const CRavidRect<int>& rect);
	CRavidLine<double> operator-(_In_ const CRavidRect<long long>& rect);
	CRavidLine<double> operator-(_In_ const CRavidRect<float>& rect);
	CRavidLine<double> operator-(_In_ const CRavidRect<double>& rect);

	CRavidLine<double> operator*(_In_ const int& value);
	CRavidLine<double> operator*(_In_ const long long& value);
	CRavidLine<double> operator*(_In_ const float& value);
	CRavidLine<double> operator*(_In_ const double& value);
	CRavidLine<double> operator*(_In_ const POINT& point);
	CRavidLine<double> operator*(_In_ const SIZE& size);
	CRavidLine<double> operator*(_In_ const RECT& rect);
	CRavidLine<double> operator*(_In_ const CRavidPoint<int>& point);
	CRavidLine<double> operator*(_In_ const CRavidPoint<long long>& point);
	CRavidLine<double> operator*(_In_ const CRavidPoint<float>& point);
	CRavidLine<double> operator*(_In_ const CRavidPoint<double>& point);
	CRavidLine<double> operator*(_In_ const CRavidLine<int>& line);
	CRavidLine<double> operator*(_In_ const CRavidLine<long long>& line);
	CRavidLine<double> operator*(_In_ const CRavidLine<float>& line);
	CRavidLine<double> operator*(_In_ const CRavidLine<double>& line);
	CRavidLine<double> operator*(_In_ const CRavidRect<int>& rect);
	CRavidLine<double> operator*(_In_ const CRavidRect<long long>& rect);
	CRavidLine<double> operator*(_In_ const CRavidRect<float>& rect);
	CRavidLine<double> operator*(_In_ const CRavidRect<double>& rect);

	CRavidLine<double> operator/(_In_ const int& value);
	CRavidLine<double> operator/(_In_ const long long& value);
	CRavidLine<double> operator/(_In_ const float& value);
	CRavidLine<double> operator/(_In_ const double& value);
	CRavidLine<double> operator/(_In_ const POINT& point);
	CRavidLine<double> operator/(_In_ const SIZE& size);
	CRavidLine<double> operator/(_In_ const RECT& rect);
	CRavidLine<double> operator/(_In_ const CRavidPoint<int>& point);
	CRavidLine<double> operator/(_In_ const CRavidPoint<long long>& point);
	CRavidLine<double> operator/(_In_ const CRavidPoint<float>& point);
	CRavidLine<double> operator/(_In_ const CRavidPoint<double>& point);
	CRavidLine<double> operator/(_In_ const CRavidLine<int>& line);
	CRavidLine<double> operator/(_In_ const CRavidLine<long long>& line);
	CRavidLine<double> operator/(_In_ const CRavidLine<float>& line);
	CRavidLine<double> operator/(_In_ const CRavidLine<double>& line);
	CRavidLine<double> operator/(_In_ const CRavidRect<int>& rect);
	CRavidLine<double> operator/(_In_ const CRavidRect<long long>& rect);
	CRavidLine<double> operator/(_In_ const CRavidRect<float>& rect);
	CRavidLine<double> operator/(_In_ const CRavidRect<double>& rect);
	//////////////////////////////////////////////////////////////////////////


	//////////////////////////////////////////////////////////////////////////
	// Casting operator
	virtual operator POINT();
	virtual operator CPoint();
	virtual operator RECT();
	virtual operator CRect();
	//////////////////////////////////////////////////////////////////////////

	virtual CRavidRect<T> GetRect();

	virtual POINT GetPointStruct() override;
	virtual RECT GetRectStruct() override;

	virtual ERavidGeometryShapeType GetShapeType();
	virtual ERavidGeometryTemplateType GetTemplateType();

	virtual CRavidGeometry* MakeDifferentTemplateType(ERavidGeometryTemplateType eType);

	virtual bool __fastcall IsValid() override;

	virtual bool IsShapeValid() override;

	CRavidPoint<double> GetCenter();
	virtual bool GetCenter(_Out_ int& x, _Out_ int& y) override;
	virtual bool GetCenter(_Out_ int* x, _Out_ int* y) override;
	virtual bool GetCenter(_Out_ long long& x, _Out_ long long& y) override;
	virtual bool GetCenter(_Out_ long long* x, _Out_ long long* y) override;
	virtual bool GetCenter(_Out_ float& x, _Out_ float& y) override;
	virtual bool GetCenter(_Out_ float* x, _Out_ float* y) override;
	virtual bool GetCenter(_Out_ double& x, _Out_ double& y) override;
	virtual bool GetCenter(_Out_ double* x, _Out_ double* y) override;
	virtual bool GetCenter(_Out_ POINT& point) override;
	virtual bool GetCenter(_Out_ POINT* pPoint) override;
	virtual bool GetCenter(_Out_ SIZE& size) override;
	virtual bool GetCenter(_Out_ SIZE* pSize) override;
	virtual bool GetCenter(_Out_ CRavidPoint<int>& point) override;
	virtual bool GetCenter(_Out_ CRavidPoint<int>* pPoint) override;
	virtual bool GetCenter(_Out_ CRavidPoint<long long>& point) override;
	virtual bool GetCenter(_Out_ CRavidPoint<long long>* pPoint) override;
	virtual bool GetCenter(_Out_ CRavidPoint<float>& point) override;
	virtual bool GetCenter(_Out_ CRavidPoint<float>* pPoint) override;
	virtual bool GetCenter(_Out_ CRavidPoint<double>& point) override;
	virtual bool GetCenter(_Out_ CRavidPoint<double>* pPoint) override;

	CRavidPoint<double> GetCenterOfGravity();
	virtual bool GetCenterOfGravity(_Out_ int& x, _Out_ int& y) override;
	virtual bool GetCenterOfGravity(_Out_ int* x, _Out_ int* y) override;
	virtual bool GetCenterOfGravity(_Out_ long long& x, _Out_ long long& y) override;
	virtual bool GetCenterOfGravity(_Out_ long long* x, _Out_ long long* y) override;
	virtual bool GetCenterOfGravity(_Out_ float& x, _Out_ float& y) override;
	virtual bool GetCenterOfGravity(_Out_ float* x, _Out_ float* y) override;
	virtual bool GetCenterOfGravity(_Out_ double& x, _Out_ double& y) override;
	virtual bool GetCenterOfGravity(_Out_ double* x, _Out_ double* y) override;
	virtual bool GetCenterOfGravity(_Out_ POINT& point) override;
	virtual bool GetCenterOfGravity(_Out_ POINT* pPoint) override;
	virtual bool GetCenterOfGravity(_Out_ SIZE& size) override;
	virtual bool GetCenterOfGravity(_Out_ SIZE* pSize) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<int>& point) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<int>* pPoint) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<long long>& point) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<long long>* pPoint) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<float>& point) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<float>* pPoint) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<double>& point) override;
	virtual bool GetCenterOfGravity(_Out_ CRavidPoint<double>* pPoint) override;

	virtual bool GetRect(_Out_ int& left, _Out_ int& top, _Out_ int& right, _Out_ int& bottom) override;
	virtual bool GetRect(_Out_ int* pLeft, _Out_ int* pTop, _Out_ int* pRight, _Out_ int* pBottom) override;
	virtual bool GetRect(_Out_ long long& left, _Out_ long long& top, _Out_ long long& right, _Out_ long long& bottom) override;
	virtual bool GetRect(_Out_ long long* pLeft, _Out_ long long* pTop, _Out_ long long* pRight, _Out_ long long* pBottom) override;
	virtual bool GetRect(_Out_ float& left, _Out_ float& top, _Out_ float& right, _Out_ float& bottom) override;
	virtual bool GetRect(_Out_ float* pLeft, _Out_ float* pTop, _Out_ float* pRight, _Out_ float* pBottom) override;
	virtual bool GetRect(_Out_ double& left, _Out_ double& top, _Out_ double& right, _Out_ double& bottom) override;
	virtual bool GetRect(_Out_ double* pLeft, _Out_ double* pTop, _Out_ double* pRight, _Out_ double* pBottom) override;
	virtual bool GetRect(_Out_ RECT& rect) override;
	virtual bool GetRect(_Out_ RECT* pRect) override;
	virtual bool GetRect(_Out_ CRavidRect<int>& rect) override;
	virtual bool GetRect(_Out_ CRavidRect<int>* pRect) override;
	virtual bool GetRect(_Out_ CRavidRect<long long>& rect) override;
	virtual bool GetRect(_Out_ CRavidRect<long long>* pRect) override;
	virtual bool GetRect(_Out_ CRavidRect<float>& rect) override;
	virtual bool GetRect(_Out_ CRavidRect<float>* pRect) override;
	virtual bool GetRect(_Out_ CRavidRect<double>& rect) override;
	virtual bool GetRect(_Out_ CRavidRect<double>* pRect) override;

	virtual bool Offset(_In_ int x, _In_ int y) override;
	virtual bool Offset(_In_ long long x, _In_ long long y) override;
	virtual bool Offset(_In_ float x, _In_ float y) override;
	virtual bool Offset(_In_ double x, _In_ double y) override;
	virtual bool Offset(_In_ POINT& point) override;
	virtual bool Offset(_In_ POINT* pPoint) override;
	virtual bool Offset(_In_ SIZE& size) override;
	virtual bool Offset(_In_ SIZE* pSize) override;
	virtual bool Offset(_In_ CRavidPoint<int>& point) override;
	virtual bool Offset(_In_ CRavidPoint<int>* pPoint) override;
	virtual bool Offset(_In_ CRavidPoint<long long>& point) override;
	virtual bool Offset(_In_ CRavidPoint<long long>* pPoint) override;
	virtual bool Offset(_In_ CRavidPoint<float>& point) override;
	virtual bool Offset(_In_ CRavidPoint<float>* pPoint) override;
	virtual bool Offset(_In_ CRavidPoint<double>& point) override;
	virtual bool Offset(_In_ CRavidPoint<double>* pPoint) override;

	virtual bool PowOffset(_In_ double powX, _In_ double powY) override;

	virtual double GetArea() override;

	virtual bool GetRasterRegion(_Out_ CRavidGeometryArray& RGA, _In_opt_ CRavidPoint<int>* pRpImageSize = nullptr) override;
	virtual bool GetRasterRegion(_Out_ CRavidGeometryArray* pRGA, _In_opt_ CRavidPoint<int>* pRpImageSize = nullptr) override;
	virtual bool GetRasterRegion(_Out_ CRavidGeometryArray& RGA, _In_opt_ CRavidRect<int>* pRrImageSize) override;
	virtual bool GetRasterRegion(_Out_ CRavidGeometryArray* pRGA, _In_opt_ CRavidRect<int>* pRrImageSize) override;


	double GetScalar();

	CRavidPoint<double> GetUnitVector();
	CRavidPoint<double> GetNormalVector();

	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ int p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ long long p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ float p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ int p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ long long p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ float p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ int p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ long long p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ float p2x, _In_ double p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ int p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ long long p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ float p2y);
	bool SetLine(_In_ double p1x, _In_ double p1y, _In_ double p2x, _In_ double p2y);
	bool SetLine(_In_ POINT& point1, _In_ POINT& point2);
	bool SetLine(_In_ POINT* pPoint1, _In_ POINT* pPoint2);
	bool SetLine(_In_ CRavidPoint<int>& point1, _In_ CRavidPoint<int>& point2);
	bool SetLine(_In_ CRavidPoint<int>* pPoint1, _In_ CRavidPoint<int>* pPoint2);
	bool SetLine(_In_ CRavidPoint<long long>& point1, _In_ CRavidPoint<long long>& point2);
	bool SetLine(_In_ CRavidPoint<long long>* pPoint1, _In_ CRavidPoint<long long>* pPoint2);
	bool SetLine(_In_ CRavidPoint<float>& point1, _In_ CRavidPoint<float>& point2);
	bool SetLine(_In_ CRavidPoint<float>* pPoint1, _In_ CRavidPoint<float>* pPoint2);
	bool SetLine(_In_ CRavidPoint<double>& point1, _In_ CRavidPoint<double>& point2);
	bool SetLine(_In_ CRavidPoint<double>* pPoint1, _In_ CRavidPoint<double>* pPoint2);
	bool SetLine(_In_ CRavidPoint<int>& rpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<int>* pRpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<long long>& rpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<long long>* pRpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<float>& rpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<float>* pRpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<double>& rpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<double>* pRpCenter, _In_ double dblAngle);
	bool SetLine(_In_ CRavidPoint<int>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<int>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<long long>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<long long>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<float>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<float>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<double>& rpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidPoint<double>* pRpCenter, _In_ double dblAngle, _In_ double dblLineLength);
	bool SetLine(_In_ CRavidLine<int>& line);
	bool SetLine(_In_ CRavidLine<int>* pLine);
	bool SetLine(_In_ CRavidLine<long long>& line);
	bool SetLine(_In_ CRavidLine<long long>* pLine);
	bool SetLine(_In_ CRavidLine<float>& line);
	bool SetLine(_In_ CRavidLine<float>* pLine);
	bool SetLine(_In_ CRavidLine<double>& line);
	bool SetLine(_In_ CRavidLine<double>* pLine);

	virtual bool Inflate(_In_ int nRadius) override;
	virtual bool Inflate(_In_ long long llRadius) override;
	virtual bool Inflate(_In_ float fRadius) override;
	virtual bool Inflate(_In_ double dblRadius) override;
	virtual bool Inflate(_In_ int left, _In_ int top, _In_ int right, _In_ int bottom) override;
	virtual bool Inflate(_In_ long long left, _In_ long long top, _In_ long long right, _In_ long long bottom) override;
	virtual bool Inflate(_In_ float left, _In_ float top, _In_ float right, _In_ float bottom) override;
	virtual bool Inflate(_In_ double left, _In_ double top, _In_ double right, _In_ double bottom) override;
	virtual bool Inflate(_In_ int width, _In_ int height) override;
	virtual bool Inflate(_In_ long long width, _In_ long long height) override;
	virtual bool Inflate(_In_ float width, _In_ float height) override;
	virtual bool Inflate(_In_ double width, _In_ double height) override;
	virtual bool Inflate(_In_ POINT& point) override;
	virtual bool Inflate(_In_ POINT* pPoint) override;
	virtual bool Inflate(_In_ SIZE& size) override;
	virtual bool Inflate(_In_ SIZE* pSize) override;
	virtual bool Inflate(_In_ CRavidPoint<int>& point) override;
	virtual bool Inflate(_In_ CRavidPoint<int>* pPoint) override;
	virtual bool Inflate(_In_ CRavidPoint<long long>& point) override;
	virtual bool Inflate(_In_ CRavidPoint<long long>* pPoint) override;
	virtual bool Inflate(_In_ CRavidPoint<float>& point) override;
	virtual bool Inflate(_In_ CRavidPoint<float>* pPoint) override;
	virtual bool Inflate(_In_ CRavidPoint<double>& point) override;
	virtual bool Inflate(_In_ CRavidPoint<double>* pPoint) override;
	virtual bool Inflate(_In_ RECT& rect) override;
	virtual bool Inflate(_In_ RECT* pRect) override;
	virtual bool Inflate(_In_ CRavidRect<int>& rect) override;
	virtual bool Inflate(_In_ CRavidRect<int>* pRect) override;
	virtual bool Inflate(_In_ CRavidRect<long long>& rect) override;
	virtual bool Inflate(_In_ CRavidRect<long long>* pRect) override;
	virtual bool Inflate(_In_ CRavidRect<float>& rect) override;
	virtual bool Inflate(_In_ CRavidRect<float>* pRect) override;
	virtual bool Inflate(_In_ CRavidRect<double>& rect) override;
	virtual bool Inflate(_In_ CRavidRect<double>* pRect) override;

	virtual bool Deflate(_In_ int nRadius) override;
	virtual bool Deflate(_In_ long long llRadius) override;
	virtual bool Deflate(_In_ float fRadius) override;
	virtual bool Deflate(_In_ double dblRadius) override;
	virtual bool Deflate(_In_ int left, _In_ int top, _In_ int right, _In_ int bottom) override;
	virtual bool Deflate(_In_ long long left, _In_ long long top, _In_ long long right, _In_ long long bottom) override;
	virtual bool Deflate(_In_ float left, _In_ float top, _In_ float right, _In_ float bottom) override;
	virtual bool Deflate(_In_ double left, _In_ double top, _In_ double right, _In_ double bottom) override;
	virtual bool Deflate(_In_ int width, _In_ int height) override;
	virtual bool Deflate(_In_ long long width, _In_ long long height) override;
	virtual bool Deflate(_In_ float width, _In_ float height) override;
	virtual bool Deflate(_In_ double width, _In_ double height) override;
	virtual bool Deflate(_In_ POINT& point) override;
	virtual bool Deflate(_In_ POINT* pPoint) override;
	virtual bool Deflate(_In_ SIZE& size) override;
	virtual bool Deflate(_In_ SIZE* pSize) override;
	virtual bool Deflate(_In_ CRavidPoint<int>& point) override;
	virtual bool Deflate(_In_ CRavidPoint<int>* pPoint) override;
	virtual bool Deflate(_In_ CRavidPoint<long long>& point) override;
	virtual bool Deflate(_In_ CRavidPoint<long long>* pPoint) override;
	virtual bool Deflate(_In_ CRavidPoint<float>& point) override;
	virtual bool Deflate(_In_ CRavidPoint<float>* pPoint) override;
	virtual bool Deflate(_In_ CRavidPoint<double>& point) override;
	virtual bool Deflate(_In_ CRavidPoint<double>* pPoint) override;
	virtual bool Deflate(_In_ RECT& rect) override;
	virtual bool Deflate(_In_ RECT* pRect) override;
	virtual bool Deflate(_In_ CRavidRect<int>& rect) override;
	virtual bool Deflate(_In_ CRavidRect<int>* pRect) override;
	virtual bool Deflate(_In_ CRavidRect<long long>& rect) override;
	virtual bool Deflate(_In_ CRavidRect<long long>* pRect) override;
	virtual bool Deflate(_In_ CRavidRect<float>& rect) override;
	virtual bool Deflate(_In_ CRavidRect<float>* pRect) override;
	virtual bool Deflate(_In_ CRavidRect<double>& rect) override;
	virtual bool Deflate(_In_ CRavidRect<double>* pRect) override;

	virtual bool Reduce(_In_ int nHalfSize);
	virtual bool Reduce(_In_ long long nHalfSize);
	virtual bool Reduce(_In_ float nHalfSize);
	virtual bool Reduce(_In_ double nHalfSize);
	virtual bool Extend(_In_ int nHalfSize);
	virtual bool Extend(_In_ long long nHalfSize);
	virtual bool Extend(_In_ float nHalfSize);
	virtual bool Extend(_In_ double nHalfSize);

	ERavidPointsDirection GetPointsDirection(_In_ double dblEndPtX, _In_ double dblEndPtY);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<int>& rpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<int>* pRpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<long long>& rpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<long long>* pRpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<float>& rpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<float>* pRpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<double>& rpEnd);
	ERavidPointsDirection GetPointsDirection(_In_ CRavidPoint<double>* pRpEnd);

	bool IsInfiniteLine();

	CRavidLine<double> GetInfiniteLine();

	bool GetEquation(_Out_ double& A, _Out_ double& B, _Out_ double& C);
	bool GetEquation(_Out_ double* pA, _Out_ double* pB, _Out_ double* pC);

	bool SetEquation(_In_ double dblA, _In_ double dblB, _In_ double dblC = 0.0);

	bool GetEquationForX(_Out_ double& dblYCoefficient, _Out_ double& dblConstant);
	bool GetEquationForX(_Out_ double* pYCoefficient, _Out_ double* pConstant);

	bool GetEquationForY(_Out_ double& dblXCoefficient, _Out_ double& dblConstant);
	bool GetEquationForY(_Out_ double* pXCoefficient, _Out_ double* pConstant);

	bool SetEquationForX(_In_ double dblYCoefficient, _In_ double dblConstant);
	bool SetEquationForY(_In_ double dblXCoefficient, _In_ double dblConstant);

	bool DoesIntersect(_In_ CRavidPoint<int>& point);
	bool DoesIntersect(_In_ CRavidPoint<int>* pPoint);
	bool DoesIntersect(_In_ CRavidPoint<long long>& point);
	bool DoesIntersect(_In_ CRavidPoint<long long>* pPoint);
	bool DoesIntersect(_In_ CRavidPoint<float>& point);
	bool DoesIntersect(_In_ CRavidPoint<float>* pPoint);
	bool DoesIntersect(_In_ CRavidPoint<double>& point);
	bool DoesIntersect(_In_ CRavidPoint<double>* pPoint);
	bool DoesIntersect(_In_ CRavidLine<int>& line);
	bool DoesIntersect(_In_ CRavidLine<int>* pLine);
	bool DoesIntersect(_In_ CRavidLine<long long>& line);
	bool DoesIntersect(_In_ CRavidLine<long long>* pLine);
	bool DoesIntersect(_In_ CRavidLine<float>& line);
	bool DoesIntersect(_In_ CRavidLine<float>* pLine);
	bool DoesIntersect(_In_ CRavidLine<double>& line);
	bool DoesIntersect(_In_ CRavidLine<double>* pLine);
	bool DoesIntersect(_In_ CRavidRect<int>& rect);
	bool DoesIntersect(_In_ CRavidRect<int>* pRect);
	bool DoesIntersect(_In_ CRavidRect<long long>& rect);
	bool DoesIntersect(_In_ CRavidRect<long long>* pRect);
	bool DoesIntersect(_In_ CRavidRect<float>& rect);
	bool DoesIntersect(_In_ CRavidRect<float>* pRect);
	bool DoesIntersect(_In_ CRavidRect<double>& rect);
	bool DoesIntersect(_In_ CRavidRect<double>* pRect);
	bool DoesIntersect(_In_ CRavidQuadrangle<int>& quad);
	bool DoesIntersect(_In_ CRavidQuadrangle<int>* pQuad);
	bool DoesIntersect(_In_ CRavidQuadrangle<long long>& quad);
	bool DoesIntersect(_In_ CRavidQuadrangle<long long>* pQuad);
	bool DoesIntersect(_In_ CRavidQuadrangle<float>& quad);
	bool DoesIntersect(_In_ CRavidQuadrangle<float>* pQuad);
	bool DoesIntersect(_In_ CRavidQuadrangle<double>& quad);
	bool DoesIntersect(_In_ CRavidQuadrangle<double>* pQuad);
	bool DoesIntersect(_In_ CRavidCircle<int>& cir);
	bool DoesIntersect(_In_ CRavidCircle<int>* pCir);
	bool DoesIntersect(_In_ CRavidCircle<long long>& cir);
	bool DoesIntersect(_In_ CRavidCircle<long long>* pCir);
	bool DoesIntersect(_In_ CRavidCircle<float>& cir);
	bool DoesIntersect(_In_ CRavidCircle<float>* pCir);
	bool DoesIntersect(_In_ CRavidCircle<double>& cir);
	bool DoesIntersect(_In_ CRavidCircle<double>* pCir);
	bool DoesIntersect(_In_ CRavidEllipse<int>& ell);
	bool DoesIntersect(_In_ CRavidEllipse<int>* pEll);
	bool DoesIntersect(_In_ CRavidEllipse<long long>& ell);
	bool DoesIntersect(_In_ CRavidEllipse<long long>* pEll);
	bool DoesIntersect(_In_ CRavidEllipse<float>& ell);
	bool DoesIntersect(_In_ CRavidEllipse<float>* pEll);
	bool DoesIntersect(_In_ CRavidEllipse<double>& ell);
	bool DoesIntersect(_In_ CRavidEllipse<double>* pEll);
	bool DoesIntersect(_In_ CRavidPolygon& rpg);
	bool DoesIntersect(_In_ CRavidPolygon* pRpg);

	CRavidPoint<double> GetIntersection(_In_ CRavidLine<int>& line);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<int>* pLine);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<long long>& line);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<long long>* pLine);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<float>& line);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<float>* pLine);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<double>& line);
	CRavidPoint<double> GetIntersection(_In_ CRavidLine<double>* pLine);

	bool GetIntersection(_In_ CRavidRect<int>& rect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<int>* pRect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<long long>& rect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<long long>* pRect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<float>& rect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<float>* pRect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<double>& rect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidRect<double>* pRect, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<int>& quad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<int>* pQuad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<long long>& quad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<long long>* pQuad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<float>& quad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<float>* pQuad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<double>& quad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidQuadrangle<double>* pQuad, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<int>& cir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<int>* pCir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<long long>& cir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<long long>* pCir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<float>& cir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<float>* pCir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<double>& cir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidCircle<double>* pCir, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<int>& ell, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<int>* pEll, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<long long>& ell, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<long long>* pEll, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<float>& ell, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<float>* pEll, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<double>& ell, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidEllipse<double>* pEll, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidPolygon& rpg, _Out_ CRavidGeometryArray* pRga);
	bool GetIntersection(_In_ CRavidPolygon* pRpg, _Out_ CRavidGeometryArray* pRga);

	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<int>& center) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<int>* pCenter) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<long long>& center) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<long long>* pCenter) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<float>& center) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<float>* pCenter) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<double>& center) override;
	virtual bool Rotate(_In_ double dblAngle, _In_ CRavidPoint<double>* pCenter) override;

	double GetOrthogonalDistance(_In_ CRavidPoint<int>& point);
	double GetOrthogonalDistance(_In_ CRavidPoint<int>* pPoint);
	double GetOrthogonalDistance(_In_ CRavidPoint<long long>& point);
	double GetOrthogonalDistance(_In_ CRavidPoint<long long>* pPoint);
	double GetOrthogonalDistance(_In_ CRavidPoint<float>& point);
	double GetOrthogonalDistance(_In_ CRavidPoint<float>* pPoint);
	double GetOrthogonalDistance(_In_ CRavidPoint<double>& point);
	double GetOrthogonalDistance(_In_ CRavidPoint<double>* pPoint);

	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<int>& point);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<int>* pPoint);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<long long>& point);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<long long>* pPoint);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<float>& point);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<float>* pPoint);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<double>& point);
	CRavidPoint<double> GetOrthogonalPoint(_In_ CRavidPoint<double>* pPoint);

	virtual double GetAngle() override;

	double GetInteriorAngle(_In_ CRavidPoint<int>& point);
	double GetInteriorAngle(_In_ CRavidPoint<int>* pPoint);
	double GetInteriorAngle(_In_ CRavidPoint<long long>& point);
	double GetInteriorAngle(_In_ CRavidPoint<long long>* pPoint);
	double GetInteriorAngle(_In_ CRavidPoint<float>& point);
	double GetInteriorAngle(_In_ CRavidPoint<float>* pPoint);
	double GetInteriorAngle(_In_ CRavidPoint<double>& point);
	double GetInteriorAngle(_In_ CRavidPoint<double>* pPoint);

	double GetInteriorAngle(_In_ CRavidLine<int>& line);
	double GetInteriorAngle(_In_ CRavidLine<int>* pLine);
	double GetInteriorAngle(_In_ CRavidLine<long long>& line);
	double GetInteriorAngle(_In_ CRavidLine<long long>* pLine);
	double GetInteriorAngle(_In_ CRavidLine<float>& line);
	double GetInteriorAngle(_In_ CRavidLine<float>* pLine);
	double GetInteriorAngle(_In_ CRavidLine<double>& line);
	double GetInteriorAngle(_In_ CRavidLine<double>* pLine);

	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<int>& point);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<int>* pPoint);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<long long>& point);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<long long>* pPoint);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<float>& point);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<float>* pPoint);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<double>& point);
	CRavidPoint<double> GetCircumcenter(_In_ CRavidPoint<double>* pPoint);

	CRavidPoint<T> rpPoints[2];

protected:
	CRavidGeometryArray* m_pExclusiveRegion = nullptr; 
};